version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_DB: accesslevels_test
      POSTGRES_USER: accesslevels_tester
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5434:5432'
